name: tweet

on:
  schedule:
    - cron: '0 * * * *'

  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump secrets
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install packages
        run: pip install python-dotenv python-youtube tweepy

      - name: Tweet
        run: python bot.py
