name: tweet

on:
  schedule:
    - cron: '0 * * * *'

  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install python-youtube tweepy

      - name: Tweet
        shell: python
        run: |
          import tweepy
          from random import choice
          from pyyoutube import Api

          api = Api(api_key="${{ secrets.YT_API_KEY }}")

          playlist = api.get_playlist_items(playlist_id="${{ secrets.YT_PLAYLIST_ID }}", count=None)
          video_id_list = [ i.snippet.resourceId.videoId for i in playlist.items ]
          video_id = choice(video_id_list)

          video = api.get_video_by_id(video_id=video_id).to_dict()
          title = video["items"][0]["snippet"]["title"]
          descr = video["items"][0]["snippet"]["description"]
          url = f"https://youtu.be/{video_id}"

          auth = tweepy.OAuthHandler("${{ secrets.APP_API_KEY }}", "${{ secrets.APP_API_SECRET_KEY }}")
          auth.set_access_token("${{ secrets.BOT_OAUTH_TOKEN }}", "${{ secrets.BOT_OAUTH_TOKEN_SECRET }}")
          api = tweepy.API(auth)

          try:
              api.verify_credentials()
              print("Authentication OK")

          except:
              print("Error during authentication")

          tweet = api.update_status(f"{title} {url}")
          reply = api.update_status(status=f"{descr}", in_reply_to_status_id=tweet.id, auto_populate_reply_metadata=True)
